Service manager rewrite
Added a slew of commands to mangage services.
Removed the use of flock
service-spawn doesn't auto fork itself

diff --git a/bin/service-manager b/bin/service-manager
--- a/bin/service-manager
+++ b/bin/service-manager
@@ -1,27 +1,37 @@
-#!/bin/sh
-set -e
+#!/bin/sh -e
 MYINIT_SERVICE_PATH=${MYINIT_SERVICE_PATH:-/etc/myinit/services.d}
 service="$2"
 [ ! -z "$service" ] && [ -f $MYINIT_SERVICE_PATH/$service ]
 case "$1" in
+create)
+    cat - > $MYINIT_SERVICE_PATH/$service
+    ;;
+delete)
+    rm $MYINIT_SERVICE_PATH/$service
+    ;;
 disable)
-    chmod u-x $MYINIT_SERVICE_PATH/$service
-	;;
+    chmod -x $MYINIT_SERVICE_PATH/$service
+    ;;
 enable)
     chmod u+x $MYINIT_SERVICE_PATH/$service
-	;;
+    ;;
+respawn)
+    kill -SIGHUP $(cat $MYINIT_SERVICE_PATH/.$service.pid)
+    ;;
+restart)
+    pkill -P $(cat $MYINIT_SERVICE_PATH/.$service.pid)
+    ;;
+signal)
+    pkill $2 -P  $(cat $MYINIT_SERVICE_PATH/.$service.pid)
+    ;;
 start)
-    service-spawn $MYINIT_SERVICE_PATH/$service
+    service-spawn $MYINIT_SERVICE_PATH/$service &
     ;;
 stop)
-    touch $MYINIT_SERVICE_PATH/.$service.down
-    pkill -L -F $MYINIT_SERVICE_PATH/.$service.pid
-	;;
-restart)
-    pkill --signal SIGUSR1 -L -F $MYINIT_SERVICE_PATH/.$service.pid
-	;;
+    kill $(cat $MYINIT_SERVICE_PATH/.$service.pid)
+    ;;
 *)
-	echo "Invalid action '$1'"
-	exit 1
-	;;
+    echo "Invalid action '$1'"
+    exit 1
+    ;;
 esac
